package client;
final class BZip2State {
   byte[] inputData;
   int inputOffset;
   int inputRemaining;
   int totalInLo32;
   int totalInHi32;
   byte[] outputData;
   int outputOffset;
   int outputRemaining;
   int totalOutLo32;
   int totalOutHi32;
   byte outputByte;
   int outputRunLength;
   boolean blockRandomized;
   int bitBuffer;
   int liveBits;
   int blockSize100k;
   int currentBlock;
   int originalPointer;
   int tPos;
   int k0;
   final int[] unzftab = new int[256];
   int nblockUsed;
   final int[] cftab = new int[257];
   public static int[] tt;
   int nInUse;
   final boolean[] inUse = new boolean[256];
   final boolean[] inUse16 = new boolean[16];
   final byte[] seqToUnseq = new byte[256];
   final byte[] mtfa = new byte[4096];
   final int[] mtfbase = new int[16];
   final byte[] selector = new byte[18002];
   final byte[] selectorMtf = new byte[18002];
   final byte[][] codeLengths = new byte[6][258];
   final int[][] huffmanLimit = new int[6][258];
   final int[][] huffmanBase = new int[6][258];
   final int[][] huffmanPerm = new int[6][258];
   final int[] minLens = new int[6];
   int nblock;
}
