package worldmap;
public final class WorldMapBZip2State {
   private int maxSelectors = 18002;
   public byte[] inputData;
   public int inputOffset = 0;
   public int inputRemaining;
   public int totalInLo32;
   public int totalInHi32;
   public byte[] outputData;
   public int outputOffset = 0;
   public int outputRemaining;
   public int totalOutLo32;
   public int totalOutHi32;
   public byte outputByte;
   public int outputRunLength;
   public boolean blockRandomized;
   public int bitBuffer;
   public int liveBits;
   public int blockSize100k;
   public int currentBlock;
   public int originalPointer;
   public int tPos;
   public int k0;
   public int[] unzftab = new int[256];
   public int nblockUsed;
   public int[] cftab = new int[257];
   public static int[] tt;
   public int nInUse;
   public boolean[] inUse = new boolean[256];
   public boolean[] inUse16 = new boolean[16];
   public byte[] seqToUnseq = new byte[256];
   public byte[] mtfa = new byte[4096];
   public int[] mtfbase = new int[16];
   public byte[] selector = new byte[this.maxSelectors];
   public byte[] selectorMtf = new byte[this.maxSelectors];
   public byte[][] codeLengths = new byte[6][258];
   public int[][] huffmanLimit = new int[6][258];
   public int[][] huffmanBase = new int[6][258];
   public int[][] huffmanPerm = new int[6][258];
   public int[] minLens = new int[6];
   public int nblock;
}
